"""initial control plane

Revision ID: 41993d3158ac
Revises:
Create Date: 2026-08-19 00:31:05.803504
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '41993d3158ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=True)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('approval_class', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_approval_class'), 'approval_requests', ['approval_class'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_name'), 'counterparties', ['name'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('model_cost_cents', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_status'), 'cycles', ['status'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('mechanism', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('expected_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('max_downside_cents', sa.Integer(), nullable=False),
    sa.Column('required_capital_cents', sa.Integer(), nullable=False),
    sa.Column('time_to_revenue_days', sa.Integer(), nullable=False),
    sa.Column('margin_bps', sa.Integer(), nullable=False),
    sa.Column('execution_difficulty', sa.Integer(), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('reversibility_bps', sa.Integer(), nullable=False),
    sa.Column('legal_risk_bps', sa.Integer(), nullable=False),
    sa.Column('evidence_strength_bps', sa.Integer(), nullable=False),
    sa.Column('score_bps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('requesting_agent', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_action_type'), 'policy_decisions', ['action_type'], unique=False)
    op.create_index(op.f('ix_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('customer_problem', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('analytics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('froze_autonomy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('owner_goal', sa.Text(), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('real_money_enabled', sa.Boolean(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('freeze_reason', sa.Text(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('global_spend_limit_cents', sa.Integer(), nullable=False),
    sa.Column('per_transaction_limit_cents', sa.Integer(), nullable=False),
    sa.Column('daily_spend_limit_cents', sa.Integer(), nullable=False),
    sa.Column('model_cost_limit_cents', sa.Integer(), nullable=False),
    sa.Column('global_spend_cents', sa.Integer(), nullable=False),
    sa.Column('daily_spend_cents', sa.Integer(), nullable=False),
    sa.Column('model_cost_cents', sa.Integer(), nullable=False),
    sa.Column('goal_reserve_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id', 'event_id', name='uq_approval_event')
    )
    op.create_index(op.f('ix_approval_events_approval_id'), 'approval_events', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_events_event'), 'approval_events', ['event'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('expected_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('max_loss_cents', sa.Integer(), nullable=False),
    sa.Column('max_spend_cents', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('kill_criteria', sa.Text(), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('owner_agent', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revenue_cents', sa.Integer(), nullable=False),
    sa.Column('expenses_cents', sa.Integer(), nullable=False),
    sa.Column('profit_cents', sa.Integer(), nullable=False),
    sa.Column('roi_bps', sa.Integer(), nullable=False),
    sa.Column('outcome_action', sa.String(length=30), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('debit_account_id', sa.String(length=36), nullable=False),
    sa.Column('credit_account_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('agent', sa.String(length=80), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_status'), 'ledger_transactions', ['status'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_kind'), 'memory_entries', ['kind'], unique=False)
    op.create_table('model_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=80), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postmortems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('money_spent_cents', sa.Integer(), nullable=False),
    sa.Column('revenue_generated_cents', sa.Integer(), nullable=False),
    sa.Column('profit_loss_cents', sa.Integer(), nullable=False),
    sa.Column('conversion_metrics', sa.JSON(), nullable=False),
    sa.Column('worked', sa.Text(), nullable=False),
    sa.Column('failed', sa.Text(), nullable=False),
    sa.Column('repeat_decision', sa.String(length=30), nullable=False),
    sa.Column('reusable_lessons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postmortems')
    op.drop_table('model_usage')
    op.drop_index(op.f('ix_memory_entries_kind'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_ledger_transactions_status'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_approval_events_event'), table_name='approval_events')
    op.drop_index(op.f('ix_approval_events_approval_id'), table_name='approval_events')
    op.drop_table('approval_events')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('projects')
    op.drop_index(op.f('ix_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_action_type'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('ledger_accounts')
    op.drop_index(op.f('ix_cycles_status'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_counterparties_name'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approval_requests_approval_class'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###

