"""portfolio streams and bug bounty controls

Revision ID: 534c2855d46b
Revises: ed30d52c5375
Create Date: 2026-08-19 00:51:07.241164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '534c2855d46b'
down_revision: Union[str, Sequence[str], None] = 'ed30d52c5375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_url', sa.Text(), nullable=False),
    sa.Column('assets_in_scope', sa.JSON(), nullable=False),
    sa.Column('assets_out_of_scope', sa.JSON(), nullable=False),
    sa.Column('safe_harbor', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('rate_limits', sa.JSON(), nullable=False),
    sa.Column('test_account_requirements', sa.Text(), nullable=False),
    sa.Column('required_headers', sa.JSON(), nullable=False),
    sa.Column('payout_tiers', sa.JSON(), nullable=False),
    sa.Column('disclosure_policy', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('owner_target_authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_assets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_scopes_status'), 'program_scopes', ['status'], unique=False)
    op.create_table('bug_bounty_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_scope_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asset', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=False),
    sa.Column('duplicate_reference', sa.String(length=300), nullable=True),
    sa.Column('payout_cents', sa.Integer(), nullable=False),
    sa.Column('payment_evidence', sa.JSON(), nullable=False),
    sa.Column('paper_outcome', sa.Boolean(), nullable=False),
    sa.Column('owner_submission_approved', sa.Boolean(), nullable=False),
    sa.Column('public_disclosure_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_scope_id'], ['program_scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_bounty_findings_program_scope_id'), 'bug_bounty_findings', ['program_scope_id'], unique=False)
    op.create_index(op.f('ix_bug_bounty_findings_status'), 'bug_bounty_findings', ['status'], unique=False)
    # Existing paper records need a deterministic legacy stream instead of a
    # nullable/unkeyed portfolio row.
    op.add_column('experiments', sa.Column('stream_type', sa.String(length=40), nullable=False, server_default=sa.text("'agent_services'")))
    op.create_index(op.f('ix_experiments_stream_type'), 'experiments', ['stream_type'], unique=False)
    op.add_column('opportunities', sa.Column('stream_type', sa.String(length=40), nullable=False, server_default=sa.text("'agent_services'")))
    op.create_index(op.f('ix_opportunities_stream_type'), 'opportunities', ['stream_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_stream_type'), table_name='opportunities')
    op.drop_column('opportunities', 'stream_type')
    op.drop_index(op.f('ix_experiments_stream_type'), table_name='experiments')
    op.drop_column('experiments', 'stream_type')
    op.drop_index(op.f('ix_bug_bounty_findings_status'), table_name='bug_bounty_findings')
    op.drop_index(op.f('ix_bug_bounty_findings_program_scope_id'), table_name='bug_bounty_findings')
    op.drop_table('bug_bounty_findings')
    op.drop_index(op.f('ix_program_scopes_status'), table_name='program_scopes')
    op.drop_table('program_scopes')
    # ### end Alembic commands ###
