"""record paper bounty payment evidence

Revision ID: 7bc41cc25c11
Revises: 534c2855d46b
Create Date: 2026-08-19 00:53:34.023414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7bc41cc25c11'
down_revision: Union[str, Sequence[str], None] = '534c2855d46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_scopes', sa.Column('payment_evidence', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('program_scopes', sa.Column('paper_outcome', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_scopes', 'paper_outcome')
    op.drop_column('program_scopes', 'payment_evidence')
    # ### end Alembic commands ###
