"""demand evidence and delivery gates

Revision ID: ed30d52c5375
Revises: 41993d3158ac
Create Date: 2026-08-19 00:41:04.727025
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ed30d52c5375'
down_revision: Union[str, Sequence[str], None] = '41993d3158ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_fk_column(
    table_name: str,
    column: sa.Column,
    constraint_name: str,
    referred_table: str,
) -> None:
    """Add a nullable FK without rebuilding referenced tables on PostgreSQL."""

    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table(table_name, recreate="always") as batch_op:
            batch_op.add_column(column)
            batch_op.create_foreign_key(
                constraint_name,
                referred_table,
                [column.name],
                ["id"],
            )
        return

    op.add_column(table_name, column)
    op.create_foreign_key(
        constraint_name,
        table_name,
        referred_table,
        [column.name],
        ["id"],
    )


def _drop_fk_column(
    table_name: str,
    column_name: str,
    constraint_name: str,
) -> None:
    """Drop a nullable FK without rebuilding referenced tables on PostgreSQL."""

    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table(table_name, recreate="always") as batch_op:
            batch_op.drop_constraint(constraint_name, type_="foreignkey")
            batch_op.drop_column(column_name)
        return

    op.drop_constraint(constraint_name, table_name, type_="foreignkey")
    op.drop_column(table_name, column_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_platform', sa.String(length=80), nullable=False),
    sa.Column('buyer_identity', sa.String(length=200), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quoted_need', sa.Text(), nullable=False),
    sa.Column('stated_budget_cents', sa.Integer(), nullable=True),
    sa.Column('stated_currency', sa.String(length=3), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('external_content_untrusted', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_negotiations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('counterparty_identity', sa.String(length=200), nullable=False),
    sa.Column('requested_product', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('agreed_price_cents', sa.Integer(), nullable=True),
    sa.Column('agreed_currency', sa.String(length=3), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counterparty_agreed', sa.Boolean(), nullable=False),
    sa.Column('owner_go', sa.Boolean(), nullable=False),
    sa.Column('owner_delivery_decision', sa.String(length=20), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('remote_ids', sa.JSON(), nullable=False),
    sa.Column('content_hashes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_negotiations_opportunity_id'), 'demand_negotiations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_demand_negotiations_state'), 'demand_negotiations', ['state'], unique=False)
    op.create_table('deliverable_proofs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_manifest', sa.JSON(), nullable=False),
    sa.Column('buyer_response', sa.String(length=30), nullable=False),
    sa.Column('acceptance', sa.String(length=30), nullable=False),
    sa.Column('settlement', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    _add_fk_column(
        "experiments",
        sa.Column("negotiation_id", sa.String(length=36), nullable=True),
        "fk_experiments_negotiation_id",
        "demand_negotiations",
    )
    _add_fk_column(
        "opportunities",
        sa.Column("demand_evidence_id", sa.String(length=36), nullable=True),
        "fk_opportunities_demand_evidence_id",
        "demand_evidence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_fk_column(
        "opportunities",
        "demand_evidence_id",
        "fk_opportunities_demand_evidence_id",
    )
    _drop_fk_column(
        "experiments",
        "negotiation_id",
        "fk_experiments_negotiation_id",
    )
    op.drop_table('deliverable_proofs')
    op.drop_index(op.f('ix_demand_negotiations_state'), table_name='demand_negotiations')
    op.drop_index(op.f('ix_demand_negotiations_opportunity_id'), table_name='demand_negotiations')
    op.drop_table('demand_negotiations')
    op.drop_table('demand_evidence')
    # ### end Alembic commands ###
